apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pp1t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pp1t
    app.kubernetes.io/part-of: tkrw-pr712-0075-0037-app
  name: devfile-sample-pp1t
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pp1t
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pp1t
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0037-tenant/tkrw-pr712-0075-0037-app/devfile-sample-pp1t@sha256:84242aaf0b049eea4873acac04fcbd92a404e76f1794156f0dd9528e77219ba6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
